name: Test ChatGPT Issue Commentator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run_chatgpt_issue_commentator:
    runs-on: ubuntu-latest
    steps:
    - name: Run ChatGPT Issue Commentator
      uses: igsr5/chatgpt-issue-commentator@v0.1.2
      with:
        openai-api-key: ${{ secrets.OEPNAI_API_KEY }}
